events {}

http {
    server {
        listen 80;
        server_name localhost;

        # api, dav, and endpoints traffic
        # no frontend traffic is proxied to the api container
        location / {
            proxy_pass http://api:3456;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}